[package]
name = "ruc"
version = "0.6.1"
authors = ["FanHui <kt71@qq.com>"]
edition = "2018"
description = "Rust Util Collection, include a friendly `error-chain` and many other utils."
keywords = ["error", "error-chain"]
categories = ["development-tools::debugging"]
license = "MIT"
homepage = "https://gitee.com/kt10/ruc"
repository = "https://gitee.com/kt10/ruc.git"

[dependencies]
lazy_static = "1.4.0"
time = "0.2.23"

[features]
ansi = []
default = ["ansi"]
