[package]
name = "myutil"
version = "0.2.1"
authors = ["范辉 <hui.fan@mail.ru>"]
edition = "2018"
description = "A simple and friendly `error-chain`."
keywords = ["error", "error-chain"]


[dependencies]
lazy_static = "1"
time = "0.2"
